version: 2

builds:
  - main: .
    binary: nownow
    ldflags:
      - -s -w -X github.com/nownow-labs/nownow/cmd.Version={{.Version}}
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: ['tar.gz']
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
