version: 2

builds:
  - id: darwin-arm64
    main: .
    binary: nownow
    ldflags:
      - -s -w -X github.com/nownow-labs/nownow/cmd.Version={{.Version}}
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - arm64
    hooks:
      post:
        - cmd: swiftc -O -target arm64-apple-macos12 -o {{ dir .Path }}/nowplaying-helper internal/detect/nowplaying/main.swift

  - id: darwin-amd64
    main: .
    binary: nownow
    ldflags:
      - -s -w -X github.com/nownow-labs/nownow/cmd.Version={{.Version}}
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      post:
        - cmd: swiftc -O -target x86_64-apple-macos12 -o {{ dir .Path }}/nowplaying-helper internal/detect/nowplaying/main.swift

  - id: cross
    main: .
    binary: nownow
    ldflags:
      - -s -w -X github.com/nownow-labs/nownow/cmd.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: darwin-arm64
    builds: [darwin-arm64]
    formats: ['tar.gz']
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: dist/darwin-arm64_darwin_arm64_v8.0/nowplaying-helper
        strip_parent: true
        info:
          mode: 0755

  - id: darwin-amd64
    builds: [darwin-amd64]
    formats: ['tar.gz']
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: dist/darwin-amd64_darwin_amd64_v1/nowplaying-helper
        strip_parent: true
        info:
          mode: 0755

  - id: cross
    builds: [cross]
    formats: ['tar.gz']
    format_overrides:
      - goos: windows
        formats: ['zip']
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
